project:
  type: manuscript
  post-render: 
   - R/cleanup.r

execute: 
  echo: true
  freeze: auto

format:
  pdf:
    documentclass: report
    classoption: 
      - 11pt
      - a4paper
    include-in-header:
      - setup/preamble.tex
    toc: false
    lang: cs
    notebook-links: false
    keep-tex: true
