project:
  type: manuscript
  post-render: 
   - R/cleanup.r

bibliography: references.bib

format:
  pdf:
    documentclass: report
    classoption: 
      - 11pt
      - a4paper
    include-in-header: setup/preamble.tex
    toc: false
    lang: cs




