Test

test

`stats::t.test()`

**test**

Jednoduchý T-test

```{r }
#| code-caption: Moje caption
#| code-label: zpracovani-python
set.seed(78)
x <- rnorm(n = 100, mean = 1, sd = 1)
t.test(x = x, mu = 0,
       alternative = "two.sided", conf.level = 0.95)
```


\ref{zpracovani-python}

Simulace alfa = chyba 1. druhu

```{r }
library(dplyr)
library(ggplot2)
# Nastavení
K   <- 1000   # Pocet simulaci
n   <- 200    # Velikost vzorku
mu0 <- 0      # Skutecny prumer
sd0 <- 2      # Populační směrodatná odchylka
alpha <- 0.05 # Hladina významnosti
set.seed(639)
vzorky <- tibble()

# Simulace
for (i in seq_len(K)) {
    x <- rnorm(n = n, mean = mu0, sd = sd0)
    test <- t.test(x = x, mu = mu0, conf.level = 1 - alpha)
    vzorky <<- bind_rows(vzorky, tibble(n = i, vysledek = test$p.value <= alpha))
}
vzorky$cvysledky <- cummean(vzorky$vysledek)
ggplot(vzorky, aes(x = n, y = cvysledky)) +
    geom_line() +
    geom_hline(aes(yintercept = .05, color = "red"), linetype = "dashed") +
    scale_y_continuous(limits = c(0, .2)) +
    scale_x_continuous(labels = scales::label_number()) +
    theme_bw() +
    labs(
        title = "Procento falešných zamítnutí h0 se blíží hladině významnosti",
        y = "Chyba I. druhu",
        x = "Počet simulací"
    )
```
